### ISSUE TITLE
Highlight the user's tweet count

### ISSUE THREAD

**Issue by giladronat** [BalestraPatrick/Tweetometer#10]
This would be lovely to see yourself in the list and tell how much _you're_ showing up in other people's timeline, since we often forget to keep track of how much we tweet in a day. Just a suggestion :smile:

**Comment by BalestraPatrick** [comment]
That's a nice idea! To achieve that, we'd need to let the user choose a specific user, load the full timeline for that specific user and perform the analysis if I am correct?

**Comment by giladronat** [comment]
Oh wow, you're proposing a cool idea but that's more advanced than what I thought. 

What I suggest is much simpler: in the analysis for the current user's timeline that shows all the tweets from other users the current user follows, also have a cell with the current user's tweet count. So for example, if I'm logged in, I'll see a breakdown of all the users I follow, as well as myself as a cell among them, telling me how many tweets **I** tweeted today.

**Comment by BalestraPatrick** [comment]
That should be done automatically. If you scroll in the users of your timeline, you can see yourself!

**Comment by giladronat** [comment]
Ah ok, fantastic in that case!
